---
- name: Create snapshot
  hosts: ontap 
  connection: local
  
  collections:
    - netapp.ontap
 
  tasks: 
    - name: Create snapshot
      na_ontap_snapshot:
        state: present
        snapshot: "{{ snapshot_name }}"
        volume: svm0_data
        comment: "Managed by Ansible"
        vserver: svm0
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        hostname: "{{ netapp_hostname }}"
        https: true
        validate_certs: false
