---
- name: Create snapshot
  hosts: ontap 
  connection: local

  vars:
    ontap_vserver: svm0
    ontap_volume: svm0_data
    ontap_vol_state: present
    ontap_comment: "Managed by Ansible"

  
  collections:
    - netapp.ontap
 
  tasks: 
    - name: Create snapshot
      na_ontap_snapshot:
        state: " {{ ontap_vol_state }}"
        snapshot: "{{ snapshot_name }}"
        volume: "{{ ontap_volume }}"
        comment: "{{ ontap_comment }}"
        vserver: "{{ ontap_vserver }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        hostname: "{{ netapp_hostname }}"
        https: true
        validate_certs: false
